#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Come2MyCityDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertUserMaster(UserMaster instance);
  partial void UpdateUserMaster(UserMaster instance);
  partial void DeleteUserMaster(UserMaster instance);
  partial void InsertCityMaster(CityMaster instance);
  partial void UpdateCityMaster(CityMaster instance);
  partial void DeleteCityMaster(CityMaster instance);
  partial void InsertFriendRelationMaster(FriendRelationMaster instance);
  partial void UpdateFriendRelationMaster(FriendRelationMaster instance);
  partial void DeleteFriendRelationMaster(FriendRelationMaster instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Come2MyCityDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<UserMaster> UserMasters
	{
		get
		{
			return this.GetTable<UserMaster>();
		}
	}
	
	public System.Data.Linq.Table<CityMaster> CityMasters
	{
		get
		{
			return this.GetTable<CityMaster>();
		}
	}
	
	public System.Data.Linq.Table<FriendGroupRelation> FriendGroupRelations
	{
		get
		{
			return this.GetTable<FriendGroupRelation>();
		}
	}
	
	public System.Data.Linq.Table<FriendRelationMaster> FriendRelationMasters
	{
		get
		{
			return this.GetTable<FriendRelationMaster>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute()]
	public ISingleResult<usp_FetchGroupMemberSendSMSResult> usp_FetchGroupMemberSendSMS([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string last, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(30)")] string first, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(5)")] string groupId)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), last, first, userId, groupId);
		return ((ISingleResult<usp_FetchGroupMemberSendSMSResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserMaster")]
public partial class UserMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _usrAutoId;
	
	private string _usrUserId;
	
	private string _usrUserName;
	
	private string _usrPassword;
	
	private string _usrFirstName;
	
	private string _usrMiddleName;
	
	private string _usrLastName;
	
	private string _usrMobileNo;
	
	private string _usrEmailId;
	
	private string _usrAddress;
	
	private string _usrState;
	
	private string _usrDistrict;
	
	private System.Nullable<int> _usrCityId;
	
	private string _usrCity;
	
	private string _usrPIN;
	
	private string _usrPhoneNo;
	
	private string _usrAltMobileNo;
	
	private string _usrDOB;
	
	private System.Nullable<int> _usrHighestQualification;
	
	private System.Nullable<int> _usrBoardUniversity;
	
	private System.Nullable<int> _usrProfession;
	
	private System.Nullable<int> _usrIndustry;
	
	private System.Nullable<int> _usrDesignation;
	
	private string _usrCompanyName;
	
	private string _usrCarrerSkill;
	
	private string _usrCarrerInterest;
	
	private string _usrIdealMatch;
	
	private string _usrBestFeature;
	
	private string _usrHeight;
	
	private string _usrBuild;
	
	private string _usrPoliticalView;
	
	private string _usrBooks;
	
	private string _usrMusic;
	
	private System.Nullable<int> _usrActive;
	
	private System.Nullable<int> _usrLogged;
	
	private string _usrProfilePhoto;
	
	private string _usrArea;
	
	private System.Nullable<int> _usrTermCond;
	
	private System.Nullable<long> _usrFriendRelId;
	
	private string _usrGender;
	
	private string _usrRecentVisitor;
	
	private System.Nullable<int> _usrControlMobileNo;
	
	private System.Nullable<int> _usrMebPolitical;
	
	private System.Nullable<int> _usrMebSocial;
	
	private System.Nullable<System.DateTime> _usrCreationDate;
	
	private System.Nullable<System.DateTime> _usrModifiedDate;
	
	private System.Nullable<System.DateTime> _usrLastLoginDate;
	
	private System.Nullable<int> _usrAgentId;
	
	private string _usrFriRelGroup;
	
	private System.Nullable<char> _isMarketingPerson;
	
	private string _OfficeNo;
	
	private string _FaxNo;
	
	private string _Website;
	
	private string _GroupId;
	
	private string _GroupName;
	
	private System.Nullable<int> _JoinFlag;
	
	private System.Nullable<int> _DND;
	
	private int _SMSbal;
	
	private int _SMSCount;
	
	private int _mCount;
	
	private int _dCount;
	
	private int _paidCount;
	
	private string _CHANGECOL;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusrAutoIdChanging(long value);
    partial void OnusrAutoIdChanged();
    partial void OnusrUserIdChanging(string value);
    partial void OnusrUserIdChanged();
    partial void OnusrUserNameChanging(string value);
    partial void OnusrUserNameChanged();
    partial void OnusrPasswordChanging(string value);
    partial void OnusrPasswordChanged();
    partial void OnusrFirstNameChanging(string value);
    partial void OnusrFirstNameChanged();
    partial void OnusrMiddleNameChanging(string value);
    partial void OnusrMiddleNameChanged();
    partial void OnusrLastNameChanging(string value);
    partial void OnusrLastNameChanged();
    partial void OnusrMobileNoChanging(string value);
    partial void OnusrMobileNoChanged();
    partial void OnusrEmailIdChanging(string value);
    partial void OnusrEmailIdChanged();
    partial void OnusrAddressChanging(string value);
    partial void OnusrAddressChanged();
    partial void OnusrStateChanging(string value);
    partial void OnusrStateChanged();
    partial void OnusrDistrictChanging(string value);
    partial void OnusrDistrictChanged();
    partial void OnusrCityIdChanging(System.Nullable<int> value);
    partial void OnusrCityIdChanged();
    partial void OnusrCityChanging(string value);
    partial void OnusrCityChanged();
    partial void OnusrPINChanging(string value);
    partial void OnusrPINChanged();
    partial void OnusrPhoneNoChanging(string value);
    partial void OnusrPhoneNoChanged();
    partial void OnusrAltMobileNoChanging(string value);
    partial void OnusrAltMobileNoChanged();
    partial void OnusrDOBChanging(string value);
    partial void OnusrDOBChanged();
    partial void OnusrHighestQualificationChanging(System.Nullable<int> value);
    partial void OnusrHighestQualificationChanged();
    partial void OnusrBoardUniversityChanging(System.Nullable<int> value);
    partial void OnusrBoardUniversityChanged();
    partial void OnusrProfessionChanging(System.Nullable<int> value);
    partial void OnusrProfessionChanged();
    partial void OnusrIndustryChanging(System.Nullable<int> value);
    partial void OnusrIndustryChanged();
    partial void OnusrDesignationChanging(System.Nullable<int> value);
    partial void OnusrDesignationChanged();
    partial void OnusrCompanyNameChanging(string value);
    partial void OnusrCompanyNameChanged();
    partial void OnusrCarrerSkillChanging(string value);
    partial void OnusrCarrerSkillChanged();
    partial void OnusrCarrerInterestChanging(string value);
    partial void OnusrCarrerInterestChanged();
    partial void OnusrIdealMatchChanging(string value);
    partial void OnusrIdealMatchChanged();
    partial void OnusrBestFeatureChanging(string value);
    partial void OnusrBestFeatureChanged();
    partial void OnusrHeightChanging(string value);
    partial void OnusrHeightChanged();
    partial void OnusrBuildChanging(string value);
    partial void OnusrBuildChanged();
    partial void OnusrPoliticalViewChanging(string value);
    partial void OnusrPoliticalViewChanged();
    partial void OnusrBooksChanging(string value);
    partial void OnusrBooksChanged();
    partial void OnusrMusicChanging(string value);
    partial void OnusrMusicChanged();
    partial void OnusrActiveChanging(System.Nullable<int> value);
    partial void OnusrActiveChanged();
    partial void OnusrLoggedChanging(System.Nullable<int> value);
    partial void OnusrLoggedChanged();
    partial void OnusrProfilePhotoChanging(string value);
    partial void OnusrProfilePhotoChanged();
    partial void OnusrAreaChanging(string value);
    partial void OnusrAreaChanged();
    partial void OnusrTermCondChanging(System.Nullable<int> value);
    partial void OnusrTermCondChanged();
    partial void OnusrFriendRelIdChanging(System.Nullable<long> value);
    partial void OnusrFriendRelIdChanged();
    partial void OnusrGenderChanging(string value);
    partial void OnusrGenderChanged();
    partial void OnusrRecentVisitorChanging(string value);
    partial void OnusrRecentVisitorChanged();
    partial void OnusrControlMobileNoChanging(System.Nullable<int> value);
    partial void OnusrControlMobileNoChanged();
    partial void OnusrMebPoliticalChanging(System.Nullable<int> value);
    partial void OnusrMebPoliticalChanged();
    partial void OnusrMebSocialChanging(System.Nullable<int> value);
    partial void OnusrMebSocialChanged();
    partial void OnusrCreationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnusrCreationDateChanged();
    partial void OnusrModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnusrModifiedDateChanged();
    partial void OnusrLastLoginDateChanging(System.Nullable<System.DateTime> value);
    partial void OnusrLastLoginDateChanged();
    partial void OnusrAgentIdChanging(System.Nullable<int> value);
    partial void OnusrAgentIdChanged();
    partial void OnusrFriRelGroupChanging(string value);
    partial void OnusrFriRelGroupChanged();
    partial void OnisMarketingPersonChanging(System.Nullable<char> value);
    partial void OnisMarketingPersonChanged();
    partial void OnOfficeNoChanging(string value);
    partial void OnOfficeNoChanged();
    partial void OnFaxNoChanging(string value);
    partial void OnFaxNoChanged();
    partial void OnWebsiteChanging(string value);
    partial void OnWebsiteChanged();
    partial void OnGroupIdChanging(string value);
    partial void OnGroupIdChanged();
    partial void OnGroupNameChanging(string value);
    partial void OnGroupNameChanged();
    partial void OnJoinFlagChanging(System.Nullable<int> value);
    partial void OnJoinFlagChanged();
    partial void OnDNDChanging(System.Nullable<int> value);
    partial void OnDNDChanged();
    partial void OnSMSbalChanging(int value);
    partial void OnSMSbalChanged();
    partial void OnSMSCountChanging(int value);
    partial void OnSMSCountChanged();
    partial void OnmCountChanging(int value);
    partial void OnmCountChanged();
    partial void OndCountChanging(int value);
    partial void OndCountChanged();
    partial void OnpaidCountChanging(int value);
    partial void OnpaidCountChanged();
    partial void OnCHANGECOLChanging(string value);
    partial void OnCHANGECOLChanged();
    #endregion
	
	public UserMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrAutoId", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
	public long usrAutoId
	{
		get
		{
			return this._usrAutoId;
		}
		set
		{
			if ((this._usrAutoId != value))
			{
				this.OnusrAutoIdChanging(value);
				this.SendPropertyChanging();
				this._usrAutoId = value;
				this.SendPropertyChanged("usrAutoId");
				this.OnusrAutoIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrUserId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string usrUserId
	{
		get
		{
			return this._usrUserId;
		}
		set
		{
			if ((this._usrUserId != value))
			{
				this.OnusrUserIdChanging(value);
				this.SendPropertyChanging();
				this._usrUserId = value;
				this.SendPropertyChanged("usrUserId");
				this.OnusrUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrUserName", DbType="NVarChar(50)")]
	public string usrUserName
	{
		get
		{
			return this._usrUserName;
		}
		set
		{
			if ((this._usrUserName != value))
			{
				this.OnusrUserNameChanging(value);
				this.SendPropertyChanging();
				this._usrUserName = value;
				this.SendPropertyChanged("usrUserName");
				this.OnusrUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrPassword", DbType="NVarChar(50)")]
	public string usrPassword
	{
		get
		{
			return this._usrPassword;
		}
		set
		{
			if ((this._usrPassword != value))
			{
				this.OnusrPasswordChanging(value);
				this.SendPropertyChanging();
				this._usrPassword = value;
				this.SendPropertyChanged("usrPassword");
				this.OnusrPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrFirstName", DbType="NVarChar(50)")]
	public string usrFirstName
	{
		get
		{
			return this._usrFirstName;
		}
		set
		{
			if ((this._usrFirstName != value))
			{
				this.OnusrFirstNameChanging(value);
				this.SendPropertyChanging();
				this._usrFirstName = value;
				this.SendPropertyChanged("usrFirstName");
				this.OnusrFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrMiddleName", DbType="NVarChar(50)")]
	public string usrMiddleName
	{
		get
		{
			return this._usrMiddleName;
		}
		set
		{
			if ((this._usrMiddleName != value))
			{
				this.OnusrMiddleNameChanging(value);
				this.SendPropertyChanging();
				this._usrMiddleName = value;
				this.SendPropertyChanged("usrMiddleName");
				this.OnusrMiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrLastName", DbType="NVarChar(50)")]
	public string usrLastName
	{
		get
		{
			return this._usrLastName;
		}
		set
		{
			if ((this._usrLastName != value))
			{
				this.OnusrLastNameChanging(value);
				this.SendPropertyChanging();
				this._usrLastName = value;
				this.SendPropertyChanged("usrLastName");
				this.OnusrLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrMobileNo", DbType="NVarChar(13)")]
	public string usrMobileNo
	{
		get
		{
			return this._usrMobileNo;
		}
		set
		{
			if ((this._usrMobileNo != value))
			{
				this.OnusrMobileNoChanging(value);
				this.SendPropertyChanging();
				this._usrMobileNo = value;
				this.SendPropertyChanged("usrMobileNo");
				this.OnusrMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrEmailId", DbType="NVarChar(50)")]
	public string usrEmailId
	{
		get
		{
			return this._usrEmailId;
		}
		set
		{
			if ((this._usrEmailId != value))
			{
				this.OnusrEmailIdChanging(value);
				this.SendPropertyChanging();
				this._usrEmailId = value;
				this.SendPropertyChanged("usrEmailId");
				this.OnusrEmailIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrAddress", DbType="NVarChar(250)")]
	public string usrAddress
	{
		get
		{
			return this._usrAddress;
		}
		set
		{
			if ((this._usrAddress != value))
			{
				this.OnusrAddressChanging(value);
				this.SendPropertyChanging();
				this._usrAddress = value;
				this.SendPropertyChanged("usrAddress");
				this.OnusrAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrState", DbType="NVarChar(50)")]
	public string usrState
	{
		get
		{
			return this._usrState;
		}
		set
		{
			if ((this._usrState != value))
			{
				this.OnusrStateChanging(value);
				this.SendPropertyChanging();
				this._usrState = value;
				this.SendPropertyChanged("usrState");
				this.OnusrStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrDistrict", DbType="NVarChar(50)")]
	public string usrDistrict
	{
		get
		{
			return this._usrDistrict;
		}
		set
		{
			if ((this._usrDistrict != value))
			{
				this.OnusrDistrictChanging(value);
				this.SendPropertyChanging();
				this._usrDistrict = value;
				this.SendPropertyChanged("usrDistrict");
				this.OnusrDistrictChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCityId", DbType="Int")]
	public System.Nullable<int> usrCityId
	{
		get
		{
			return this._usrCityId;
		}
		set
		{
			if ((this._usrCityId != value))
			{
				this.OnusrCityIdChanging(value);
				this.SendPropertyChanging();
				this._usrCityId = value;
				this.SendPropertyChanged("usrCityId");
				this.OnusrCityIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCity", DbType="NVarChar(50)")]
	public string usrCity
	{
		get
		{
			return this._usrCity;
		}
		set
		{
			if ((this._usrCity != value))
			{
				this.OnusrCityChanging(value);
				this.SendPropertyChanging();
				this._usrCity = value;
				this.SendPropertyChanged("usrCity");
				this.OnusrCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrPIN", DbType="NVarChar(6)")]
	public string usrPIN
	{
		get
		{
			return this._usrPIN;
		}
		set
		{
			if ((this._usrPIN != value))
			{
				this.OnusrPINChanging(value);
				this.SendPropertyChanging();
				this._usrPIN = value;
				this.SendPropertyChanged("usrPIN");
				this.OnusrPINChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrPhoneNo", DbType="NVarChar(15)")]
	public string usrPhoneNo
	{
		get
		{
			return this._usrPhoneNo;
		}
		set
		{
			if ((this._usrPhoneNo != value))
			{
				this.OnusrPhoneNoChanging(value);
				this.SendPropertyChanging();
				this._usrPhoneNo = value;
				this.SendPropertyChanged("usrPhoneNo");
				this.OnusrPhoneNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrAltMobileNo", DbType="NVarChar(13)")]
	public string usrAltMobileNo
	{
		get
		{
			return this._usrAltMobileNo;
		}
		set
		{
			if ((this._usrAltMobileNo != value))
			{
				this.OnusrAltMobileNoChanging(value);
				this.SendPropertyChanging();
				this._usrAltMobileNo = value;
				this.SendPropertyChanged("usrAltMobileNo");
				this.OnusrAltMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrDOB", DbType="NVarChar(10)")]
	public string usrDOB
	{
		get
		{
			return this._usrDOB;
		}
		set
		{
			if ((this._usrDOB != value))
			{
				this.OnusrDOBChanging(value);
				this.SendPropertyChanging();
				this._usrDOB = value;
				this.SendPropertyChanged("usrDOB");
				this.OnusrDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrHighestQualification", DbType="Int")]
	public System.Nullable<int> usrHighestQualification
	{
		get
		{
			return this._usrHighestQualification;
		}
		set
		{
			if ((this._usrHighestQualification != value))
			{
				this.OnusrHighestQualificationChanging(value);
				this.SendPropertyChanging();
				this._usrHighestQualification = value;
				this.SendPropertyChanged("usrHighestQualification");
				this.OnusrHighestQualificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrBoardUniversity", DbType="Int")]
	public System.Nullable<int> usrBoardUniversity
	{
		get
		{
			return this._usrBoardUniversity;
		}
		set
		{
			if ((this._usrBoardUniversity != value))
			{
				this.OnusrBoardUniversityChanging(value);
				this.SendPropertyChanging();
				this._usrBoardUniversity = value;
				this.SendPropertyChanged("usrBoardUniversity");
				this.OnusrBoardUniversityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrProfession", DbType="Int")]
	public System.Nullable<int> usrProfession
	{
		get
		{
			return this._usrProfession;
		}
		set
		{
			if ((this._usrProfession != value))
			{
				this.OnusrProfessionChanging(value);
				this.SendPropertyChanging();
				this._usrProfession = value;
				this.SendPropertyChanged("usrProfession");
				this.OnusrProfessionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrIndustry", DbType="Int")]
	public System.Nullable<int> usrIndustry
	{
		get
		{
			return this._usrIndustry;
		}
		set
		{
			if ((this._usrIndustry != value))
			{
				this.OnusrIndustryChanging(value);
				this.SendPropertyChanging();
				this._usrIndustry = value;
				this.SendPropertyChanged("usrIndustry");
				this.OnusrIndustryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrDesignation", DbType="Int")]
	public System.Nullable<int> usrDesignation
	{
		get
		{
			return this._usrDesignation;
		}
		set
		{
			if ((this._usrDesignation != value))
			{
				this.OnusrDesignationChanging(value);
				this.SendPropertyChanging();
				this._usrDesignation = value;
				this.SendPropertyChanged("usrDesignation");
				this.OnusrDesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCompanyName", DbType="NVarChar(350)")]
	public string usrCompanyName
	{
		get
		{
			return this._usrCompanyName;
		}
		set
		{
			if ((this._usrCompanyName != value))
			{
				this.OnusrCompanyNameChanging(value);
				this.SendPropertyChanging();
				this._usrCompanyName = value;
				this.SendPropertyChanged("usrCompanyName");
				this.OnusrCompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCarrerSkill", DbType="NVarChar(350)")]
	public string usrCarrerSkill
	{
		get
		{
			return this._usrCarrerSkill;
		}
		set
		{
			if ((this._usrCarrerSkill != value))
			{
				this.OnusrCarrerSkillChanging(value);
				this.SendPropertyChanging();
				this._usrCarrerSkill = value;
				this.SendPropertyChanged("usrCarrerSkill");
				this.OnusrCarrerSkillChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCarrerInterest", DbType="NVarChar(350)")]
	public string usrCarrerInterest
	{
		get
		{
			return this._usrCarrerInterest;
		}
		set
		{
			if ((this._usrCarrerInterest != value))
			{
				this.OnusrCarrerInterestChanging(value);
				this.SendPropertyChanging();
				this._usrCarrerInterest = value;
				this.SendPropertyChanged("usrCarrerInterest");
				this.OnusrCarrerInterestChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrIdealMatch", DbType="NVarChar(350)")]
	public string usrIdealMatch
	{
		get
		{
			return this._usrIdealMatch;
		}
		set
		{
			if ((this._usrIdealMatch != value))
			{
				this.OnusrIdealMatchChanging(value);
				this.SendPropertyChanging();
				this._usrIdealMatch = value;
				this.SendPropertyChanged("usrIdealMatch");
				this.OnusrIdealMatchChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrBestFeature", DbType="NVarChar(350)")]
	public string usrBestFeature
	{
		get
		{
			return this._usrBestFeature;
		}
		set
		{
			if ((this._usrBestFeature != value))
			{
				this.OnusrBestFeatureChanging(value);
				this.SendPropertyChanging();
				this._usrBestFeature = value;
				this.SendPropertyChanged("usrBestFeature");
				this.OnusrBestFeatureChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrHeight", DbType="NVarChar(10)")]
	public string usrHeight
	{
		get
		{
			return this._usrHeight;
		}
		set
		{
			if ((this._usrHeight != value))
			{
				this.OnusrHeightChanging(value);
				this.SendPropertyChanging();
				this._usrHeight = value;
				this.SendPropertyChanged("usrHeight");
				this.OnusrHeightChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrBuild", DbType="NVarChar(10)")]
	public string usrBuild
	{
		get
		{
			return this._usrBuild;
		}
		set
		{
			if ((this._usrBuild != value))
			{
				this.OnusrBuildChanging(value);
				this.SendPropertyChanging();
				this._usrBuild = value;
				this.SendPropertyChanged("usrBuild");
				this.OnusrBuildChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrPoliticalView", DbType="NVarChar(350)")]
	public string usrPoliticalView
	{
		get
		{
			return this._usrPoliticalView;
		}
		set
		{
			if ((this._usrPoliticalView != value))
			{
				this.OnusrPoliticalViewChanging(value);
				this.SendPropertyChanging();
				this._usrPoliticalView = value;
				this.SendPropertyChanged("usrPoliticalView");
				this.OnusrPoliticalViewChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrBooks", DbType="NVarChar(350)")]
	public string usrBooks
	{
		get
		{
			return this._usrBooks;
		}
		set
		{
			if ((this._usrBooks != value))
			{
				this.OnusrBooksChanging(value);
				this.SendPropertyChanging();
				this._usrBooks = value;
				this.SendPropertyChanged("usrBooks");
				this.OnusrBooksChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrMusic", DbType="NVarChar(350)")]
	public string usrMusic
	{
		get
		{
			return this._usrMusic;
		}
		set
		{
			if ((this._usrMusic != value))
			{
				this.OnusrMusicChanging(value);
				this.SendPropertyChanging();
				this._usrMusic = value;
				this.SendPropertyChanged("usrMusic");
				this.OnusrMusicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrActive", DbType="Int")]
	public System.Nullable<int> usrActive
	{
		get
		{
			return this._usrActive;
		}
		set
		{
			if ((this._usrActive != value))
			{
				this.OnusrActiveChanging(value);
				this.SendPropertyChanging();
				this._usrActive = value;
				this.SendPropertyChanged("usrActive");
				this.OnusrActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrLogged", DbType="Int")]
	public System.Nullable<int> usrLogged
	{
		get
		{
			return this._usrLogged;
		}
		set
		{
			if ((this._usrLogged != value))
			{
				this.OnusrLoggedChanging(value);
				this.SendPropertyChanging();
				this._usrLogged = value;
				this.SendPropertyChanged("usrLogged");
				this.OnusrLoggedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrProfilePhoto", DbType="NVarChar(100)")]
	public string usrProfilePhoto
	{
		get
		{
			return this._usrProfilePhoto;
		}
		set
		{
			if ((this._usrProfilePhoto != value))
			{
				this.OnusrProfilePhotoChanging(value);
				this.SendPropertyChanging();
				this._usrProfilePhoto = value;
				this.SendPropertyChanged("usrProfilePhoto");
				this.OnusrProfilePhotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrArea", DbType="NVarChar(250)")]
	public string usrArea
	{
		get
		{
			return this._usrArea;
		}
		set
		{
			if ((this._usrArea != value))
			{
				this.OnusrAreaChanging(value);
				this.SendPropertyChanging();
				this._usrArea = value;
				this.SendPropertyChanged("usrArea");
				this.OnusrAreaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrTermCond", DbType="Int")]
	public System.Nullable<int> usrTermCond
	{
		get
		{
			return this._usrTermCond;
		}
		set
		{
			if ((this._usrTermCond != value))
			{
				this.OnusrTermCondChanging(value);
				this.SendPropertyChanging();
				this._usrTermCond = value;
				this.SendPropertyChanged("usrTermCond");
				this.OnusrTermCondChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrFriendRelId", DbType="BigInt")]
	public System.Nullable<long> usrFriendRelId
	{
		get
		{
			return this._usrFriendRelId;
		}
		set
		{
			if ((this._usrFriendRelId != value))
			{
				this.OnusrFriendRelIdChanging(value);
				this.SendPropertyChanging();
				this._usrFriendRelId = value;
				this.SendPropertyChanged("usrFriendRelId");
				this.OnusrFriendRelIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrGender", DbType="NVarChar(8)")]
	public string usrGender
	{
		get
		{
			return this._usrGender;
		}
		set
		{
			if ((this._usrGender != value))
			{
				this.OnusrGenderChanging(value);
				this.SendPropertyChanging();
				this._usrGender = value;
				this.SendPropertyChanged("usrGender");
				this.OnusrGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrRecentVisitor", DbType="NVarChar(500)")]
	public string usrRecentVisitor
	{
		get
		{
			return this._usrRecentVisitor;
		}
		set
		{
			if ((this._usrRecentVisitor != value))
			{
				this.OnusrRecentVisitorChanging(value);
				this.SendPropertyChanging();
				this._usrRecentVisitor = value;
				this.SendPropertyChanged("usrRecentVisitor");
				this.OnusrRecentVisitorChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrControlMobileNo", DbType="Int")]
	public System.Nullable<int> usrControlMobileNo
	{
		get
		{
			return this._usrControlMobileNo;
		}
		set
		{
			if ((this._usrControlMobileNo != value))
			{
				this.OnusrControlMobileNoChanging(value);
				this.SendPropertyChanging();
				this._usrControlMobileNo = value;
				this.SendPropertyChanged("usrControlMobileNo");
				this.OnusrControlMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrMebPolitical", DbType="Int")]
	public System.Nullable<int> usrMebPolitical
	{
		get
		{
			return this._usrMebPolitical;
		}
		set
		{
			if ((this._usrMebPolitical != value))
			{
				this.OnusrMebPoliticalChanging(value);
				this.SendPropertyChanging();
				this._usrMebPolitical = value;
				this.SendPropertyChanged("usrMebPolitical");
				this.OnusrMebPoliticalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrMebSocial", DbType="Int")]
	public System.Nullable<int> usrMebSocial
	{
		get
		{
			return this._usrMebSocial;
		}
		set
		{
			if ((this._usrMebSocial != value))
			{
				this.OnusrMebSocialChanging(value);
				this.SendPropertyChanging();
				this._usrMebSocial = value;
				this.SendPropertyChanged("usrMebSocial");
				this.OnusrMebSocialChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCreationDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> usrCreationDate
	{
		get
		{
			return this._usrCreationDate;
		}
		set
		{
			if ((this._usrCreationDate != value))
			{
				this.OnusrCreationDateChanging(value);
				this.SendPropertyChanging();
				this._usrCreationDate = value;
				this.SendPropertyChanged("usrCreationDate");
				this.OnusrCreationDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrModifiedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> usrModifiedDate
	{
		get
		{
			return this._usrModifiedDate;
		}
		set
		{
			if ((this._usrModifiedDate != value))
			{
				this.OnusrModifiedDateChanging(value);
				this.SendPropertyChanging();
				this._usrModifiedDate = value;
				this.SendPropertyChanged("usrModifiedDate");
				this.OnusrModifiedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrLastLoginDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> usrLastLoginDate
	{
		get
		{
			return this._usrLastLoginDate;
		}
		set
		{
			if ((this._usrLastLoginDate != value))
			{
				this.OnusrLastLoginDateChanging(value);
				this.SendPropertyChanging();
				this._usrLastLoginDate = value;
				this.SendPropertyChanged("usrLastLoginDate");
				this.OnusrLastLoginDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrAgentId", DbType="Int")]
	public System.Nullable<int> usrAgentId
	{
		get
		{
			return this._usrAgentId;
		}
		set
		{
			if ((this._usrAgentId != value))
			{
				this.OnusrAgentIdChanging(value);
				this.SendPropertyChanging();
				this._usrAgentId = value;
				this.SendPropertyChanged("usrAgentId");
				this.OnusrAgentIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrFriRelGroup", DbType="NVarChar(100)")]
	public string usrFriRelGroup
	{
		get
		{
			return this._usrFriRelGroup;
		}
		set
		{
			if ((this._usrFriRelGroup != value))
			{
				this.OnusrFriRelGroupChanging(value);
				this.SendPropertyChanging();
				this._usrFriRelGroup = value;
				this.SendPropertyChanged("usrFriRelGroup");
				this.OnusrFriRelGroupChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isMarketingPerson", DbType="NVarChar(1)")]
	public System.Nullable<char> isMarketingPerson
	{
		get
		{
			return this._isMarketingPerson;
		}
		set
		{
			if ((this._isMarketingPerson != value))
			{
				this.OnisMarketingPersonChanging(value);
				this.SendPropertyChanging();
				this._isMarketingPerson = value;
				this.SendPropertyChanged("isMarketingPerson");
				this.OnisMarketingPersonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeNo", DbType="NVarChar(15)")]
	public string OfficeNo
	{
		get
		{
			return this._OfficeNo;
		}
		set
		{
			if ((this._OfficeNo != value))
			{
				this.OnOfficeNoChanging(value);
				this.SendPropertyChanging();
				this._OfficeNo = value;
				this.SendPropertyChanged("OfficeNo");
				this.OnOfficeNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FaxNo", DbType="NVarChar(15)")]
	public string FaxNo
	{
		get
		{
			return this._FaxNo;
		}
		set
		{
			if ((this._FaxNo != value))
			{
				this.OnFaxNoChanging(value);
				this.SendPropertyChanging();
				this._FaxNo = value;
				this.SendPropertyChanged("FaxNo");
				this.OnFaxNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Website", DbType="NVarChar(100)")]
	public string Website
	{
		get
		{
			return this._Website;
		}
		set
		{
			if ((this._Website != value))
			{
				this.OnWebsiteChanging(value);
				this.SendPropertyChanging();
				this._Website = value;
				this.SendPropertyChanged("Website");
				this.OnWebsiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="NVarChar(100)")]
	public string GroupId
	{
		get
		{
			return this._GroupId;
		}
		set
		{
			if ((this._GroupId != value))
			{
				this.OnGroupIdChanging(value);
				this.SendPropertyChanging();
				this._GroupId = value;
				this.SendPropertyChanged("GroupId");
				this.OnGroupIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupName", DbType="NVarChar(1000)")]
	public string GroupName
	{
		get
		{
			return this._GroupName;
		}
		set
		{
			if ((this._GroupName != value))
			{
				this.OnGroupNameChanging(value);
				this.SendPropertyChanging();
				this._GroupName = value;
				this.SendPropertyChanged("GroupName");
				this.OnGroupNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JoinFlag", DbType="Int")]
	public System.Nullable<int> JoinFlag
	{
		get
		{
			return this._JoinFlag;
		}
		set
		{
			if ((this._JoinFlag != value))
			{
				this.OnJoinFlagChanging(value);
				this.SendPropertyChanging();
				this._JoinFlag = value;
				this.SendPropertyChanged("JoinFlag");
				this.OnJoinFlagChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DND", DbType="Int")]
	public System.Nullable<int> DND
	{
		get
		{
			return this._DND;
		}
		set
		{
			if ((this._DND != value))
			{
				this.OnDNDChanging(value);
				this.SendPropertyChanging();
				this._DND = value;
				this.SendPropertyChanged("DND");
				this.OnDNDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSbal", DbType="Int NOT NULL")]
	public int SMSbal
	{
		get
		{
			return this._SMSbal;
		}
		set
		{
			if ((this._SMSbal != value))
			{
				this.OnSMSbalChanging(value);
				this.SendPropertyChanging();
				this._SMSbal = value;
				this.SendPropertyChanged("SMSbal");
				this.OnSMSbalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSCount", DbType="Int NOT NULL")]
	public int SMSCount
	{
		get
		{
			return this._SMSCount;
		}
		set
		{
			if ((this._SMSCount != value))
			{
				this.OnSMSCountChanging(value);
				this.SendPropertyChanging();
				this._SMSCount = value;
				this.SendPropertyChanged("SMSCount");
				this.OnSMSCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mCount", DbType="Int NOT NULL")]
	public int mCount
	{
		get
		{
			return this._mCount;
		}
		set
		{
			if ((this._mCount != value))
			{
				this.OnmCountChanging(value);
				this.SendPropertyChanging();
				this._mCount = value;
				this.SendPropertyChanged("mCount");
				this.OnmCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dCount", DbType="Int NOT NULL")]
	public int dCount
	{
		get
		{
			return this._dCount;
		}
		set
		{
			if ((this._dCount != value))
			{
				this.OndCountChanging(value);
				this.SendPropertyChanging();
				this._dCount = value;
				this.SendPropertyChanged("dCount");
				this.OndCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paidCount", DbType="Int NOT NULL")]
	public int paidCount
	{
		get
		{
			return this._paidCount;
		}
		set
		{
			if ((this._paidCount != value))
			{
				this.OnpaidCountChanging(value);
				this.SendPropertyChanging();
				this._paidCount = value;
				this.SendPropertyChanged("paidCount");
				this.OnpaidCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHANGECOL", DbType="NVarChar(500)")]
	public string CHANGECOL
	{
		get
		{
			return this._CHANGECOL;
		}
		set
		{
			if ((this._CHANGECOL != value))
			{
				this.OnCHANGECOLChanging(value);
				this.SendPropertyChanging();
				this._CHANGECOL = value;
				this.SendPropertyChanged("CHANGECOL");
				this.OnCHANGECOLChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CityMaster")]
public partial class CityMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cityId;
	
	private string _cityName;
	
	private System.Nullable<int> _distId;
	
	private System.Nullable<int> _stateId;
	
	private System.Nullable<int> _cityActive;
	
	private System.Nullable<int> _PIN;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncityIdChanging(int value);
    partial void OncityIdChanged();
    partial void OncityNameChanging(string value);
    partial void OncityNameChanged();
    partial void OndistIdChanging(System.Nullable<int> value);
    partial void OndistIdChanged();
    partial void OnstateIdChanging(System.Nullable<int> value);
    partial void OnstateIdChanged();
    partial void OncityActiveChanging(System.Nullable<int> value);
    partial void OncityActiveChanged();
    partial void OnPINChanging(System.Nullable<int> value);
    partial void OnPINChanged();
    #endregion
	
	public CityMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityId", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int cityId
	{
		get
		{
			return this._cityId;
		}
		set
		{
			if ((this._cityId != value))
			{
				this.OncityIdChanging(value);
				this.SendPropertyChanging();
				this._cityId = value;
				this.SendPropertyChanged("cityId");
				this.OncityIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityName", DbType="NVarChar(350)")]
	public string cityName
	{
		get
		{
			return this._cityName;
		}
		set
		{
			if ((this._cityName != value))
			{
				this.OncityNameChanging(value);
				this.SendPropertyChanging();
				this._cityName = value;
				this.SendPropertyChanged("cityName");
				this.OncityNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distId", DbType="Int")]
	public System.Nullable<int> distId
	{
		get
		{
			return this._distId;
		}
		set
		{
			if ((this._distId != value))
			{
				this.OndistIdChanging(value);
				this.SendPropertyChanging();
				this._distId = value;
				this.SendPropertyChanged("distId");
				this.OndistIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stateId", DbType="Int")]
	public System.Nullable<int> stateId
	{
		get
		{
			return this._stateId;
		}
		set
		{
			if ((this._stateId != value))
			{
				this.OnstateIdChanging(value);
				this.SendPropertyChanging();
				this._stateId = value;
				this.SendPropertyChanged("stateId");
				this.OnstateIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cityActive", DbType="Int")]
	public System.Nullable<int> cityActive
	{
		get
		{
			return this._cityActive;
		}
		set
		{
			if ((this._cityActive != value))
			{
				this.OncityActiveChanging(value);
				this.SendPropertyChanging();
				this._cityActive = value;
				this.SendPropertyChanged("cityActive");
				this.OncityActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIN", DbType="Int")]
	public System.Nullable<int> PIN
	{
		get
		{
			return this._PIN;
		}
		set
		{
			if ((this._PIN != value))
			{
				this.OnPINChanging(value);
				this.SendPropertyChanging();
				this._PIN = value;
				this.SendPropertyChanged("PIN");
				this.OnPINChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FriendGroupRelation")]
public partial class FriendGroupRelation
{
	
	private System.Nullable<int> _RelId;
	
	private System.Nullable<int> _GroupId;
	
	public FriendGroupRelation()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RelId", DbType="Int")]
	public System.Nullable<int> RelId
	{
		get
		{
			return this._RelId;
		}
		set
		{
			if ((this._RelId != value))
			{
				this._RelId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupId", DbType="Int")]
	public System.Nullable<int> GroupId
	{
		get
		{
			return this._GroupId;
		}
		set
		{
			if ((this._GroupId != value))
			{
				this._GroupId = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FriendRelationMaster")]
public partial class FriendRelationMaster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _FriRelId;
	
	private string _UserId;
	
	private string _FriendId;
	
	private string _FriRelName;
	
	private string _Relation;
	
	private System.Nullable<int> _Active;
	
	private string _friendGroup;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFriRelIdChanging(long value);
    partial void OnFriRelIdChanged();
    partial void OnUserIdChanging(string value);
    partial void OnUserIdChanged();
    partial void OnFriendIdChanging(string value);
    partial void OnFriendIdChanged();
    partial void OnFriRelNameChanging(string value);
    partial void OnFriRelNameChanged();
    partial void OnRelationChanging(string value);
    partial void OnRelationChanged();
    partial void OnActiveChanging(System.Nullable<int> value);
    partial void OnActiveChanged();
    partial void OnfriendGroupChanging(string value);
    partial void OnfriendGroupChanged();
    #endregion
	
	public FriendRelationMaster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriRelId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long FriRelId
	{
		get
		{
			return this._FriRelId;
		}
		set
		{
			if ((this._FriRelId != value))
			{
				this.OnFriRelIdChanging(value);
				this.SendPropertyChanging();
				this._FriRelId = value;
				this.SendPropertyChanged("FriRelId");
				this.OnFriRelIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="NVarChar(40)")]
	public string UserId
	{
		get
		{
			return this._UserId;
		}
		set
		{
			if ((this._UserId != value))
			{
				this.OnUserIdChanging(value);
				this.SendPropertyChanging();
				this._UserId = value;
				this.SendPropertyChanged("UserId");
				this.OnUserIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriendId", DbType="NVarChar(40)")]
	public string FriendId
	{
		get
		{
			return this._FriendId;
		}
		set
		{
			if ((this._FriendId != value))
			{
				this.OnFriendIdChanging(value);
				this.SendPropertyChanging();
				this._FriendId = value;
				this.SendPropertyChanged("FriendId");
				this.OnFriendIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FriRelName", DbType="NVarChar(250)")]
	public string FriRelName
	{
		get
		{
			return this._FriRelName;
		}
		set
		{
			if ((this._FriRelName != value))
			{
				this.OnFriRelNameChanging(value);
				this.SendPropertyChanging();
				this._FriRelName = value;
				this.SendPropertyChanged("FriRelName");
				this.OnFriRelNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relation", DbType="VarChar(100)")]
	public string Relation
	{
		get
		{
			return this._Relation;
		}
		set
		{
			if ((this._Relation != value))
			{
				this.OnRelationChanging(value);
				this.SendPropertyChanging();
				this._Relation = value;
				this.SendPropertyChanged("Relation");
				this.OnRelationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Active", DbType="Int")]
	public System.Nullable<int> Active
	{
		get
		{
			return this._Active;
		}
		set
		{
			if ((this._Active != value))
			{
				this.OnActiveChanging(value);
				this.SendPropertyChanging();
				this._Active = value;
				this.SendPropertyChanged("Active");
				this.OnActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_friendGroup", DbType="NVarChar(50)")]
	public string friendGroup
	{
		get
		{
			return this._friendGroup;
		}
		set
		{
			if ((this._friendGroup != value))
			{
				this.OnfriendGroupChanging(value);
				this.SendPropertyChanging();
				this._friendGroup = value;
				this.SendPropertyChanged("friendGroup");
				this.OnfriendGroupChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class usp_FetchGroupMemberSendSMSResult
{
	
	private string _usrUserId;
	
	private string _usrFirstName;
	
	private string _usrLastName;
	
	private string _usrProfilePhoto;
	
	private string _usrCity;
	
	private string _usrFullName;
	
	private string _usrMobileNo;
	
	private System.Nullable<long> _rowNumber;
	
	public usp_FetchGroupMemberSendSMSResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrUserId", DbType="NVarChar(50)")]
	public string usrUserId
	{
		get
		{
			return this._usrUserId;
		}
		set
		{
			if ((this._usrUserId != value))
			{
				this._usrUserId = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrFirstName", DbType="NVarChar(50)")]
	public string usrFirstName
	{
		get
		{
			return this._usrFirstName;
		}
		set
		{
			if ((this._usrFirstName != value))
			{
				this._usrFirstName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrLastName", DbType="NVarChar(50)")]
	public string usrLastName
	{
		get
		{
			return this._usrLastName;
		}
		set
		{
			if ((this._usrLastName != value))
			{
				this._usrLastName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrProfilePhoto", DbType="NVarChar(181)")]
	public string usrProfilePhoto
	{
		get
		{
			return this._usrProfilePhoto;
		}
		set
		{
			if ((this._usrProfilePhoto != value))
			{
				this._usrProfilePhoto = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrCity", DbType="NVarChar(350)")]
	public string usrCity
	{
		get
		{
			return this._usrCity;
		}
		set
		{
			if ((this._usrCity != value))
			{
				this._usrCity = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrFullName", DbType="NVarChar(101)")]
	public string usrFullName
	{
		get
		{
			return this._usrFullName;
		}
		set
		{
			if ((this._usrFullName != value))
			{
				this._usrFullName = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usrMobileNo", DbType="NVarChar(13)")]
	public string usrMobileNo
	{
		get
		{
			return this._usrMobileNo;
		}
		set
		{
			if ((this._usrMobileNo != value))
			{
				this._usrMobileNo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rowNumber", DbType="BigInt")]
	public System.Nullable<long> rowNumber
	{
		get
		{
			return this._rowNumber;
		}
		set
		{
			if ((this._rowNumber != value))
			{
				this._rowNumber = value;
			}
		}
	}
}
#pragma warning restore 1591
