#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Come2MyCityDB")]
public partial class PaidSmsDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertsendPaidSmsStatus(sendPaidSmsStatus instance);
  partial void UpdatesendPaidSmsStatus(sendPaidSmsStatus instance);
  partial void DeletesendPaidSmsStatus(sendPaidSmsStatus instance);
  #endregion
	
	public PaidSmsDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Come2MyCityDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PaidSmsDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PaidSmsDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PaidSmsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PaidSmsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<sendPaidSmsStatus> sendPaidSmsStatus
	{
		get
		{
			return this.GetTable<sendPaidSmsStatus>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute()]
	public int InsertPaidSMs([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SendFrom", DbType="NVarChar(15)")] string sendFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string sendTo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string sms, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string status)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sendFrom, sendTo, sms, status);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute()]
	public ISingleResult<SearchPaidSMsResult> SearchPaidSMs([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SendFrom", DbType="NVarChar(15)")] string sendFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string sendUpTo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(15)")] string sender)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sendFrom, sendUpTo, sender);
		return ((ISingleResult<SearchPaidSMsResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute()]
public partial class sendPaidSmsStatus : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _SendFron;
	
	private string _SendTo;
	
	private string _sms;
	
	private string _FlagStatus;
	
	private System.Nullable<System.DateTime> _sendDateTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSendFronChanging(string value);
    partial void OnSendFronChanged();
    partial void OnSendToChanging(string value);
    partial void OnSendToChanged();
    partial void OnsmsChanging(string value);
    partial void OnsmsChanged();
    partial void OnFlagStatusChanging(string value);
    partial void OnFlagStatusChanged();
    partial void OnsendDateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnsendDateTimeChanged();
    #endregion
	
	public sendPaidSmsStatus()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendFron", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string SendFron
	{
		get
		{
			return this._SendFron;
		}
		set
		{
			if ((this._SendFron != value))
			{
				this.OnSendFronChanging(value);
				this.SendPropertyChanging();
				this._SendFron = value;
				this.SendPropertyChanged("SendFron");
				this.OnSendFronChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendTo", DbType="NVarChar(15)")]
	public string SendTo
	{
		get
		{
			return this._SendTo;
		}
		set
		{
			if ((this._SendTo != value))
			{
				this.OnSendToChanging(value);
				this.SendPropertyChanging();
				this._SendTo = value;
				this.SendPropertyChanged("SendTo");
				this.OnSendToChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sms", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string sms
	{
		get
		{
			return this._sms;
		}
		set
		{
			if ((this._sms != value))
			{
				this.OnsmsChanging(value);
				this.SendPropertyChanging();
				this._sms = value;
				this.SendPropertyChanged("sms");
				this.OnsmsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagStatus", DbType="NVarChar(50)")]
	public string FlagStatus
	{
		get
		{
			return this._FlagStatus;
		}
		set
		{
			if ((this._FlagStatus != value))
			{
				this.OnFlagStatusChanging(value);
				this.SendPropertyChanging();
				this._FlagStatus = value;
				this.SendPropertyChanged("FlagStatus");
				this.OnFlagStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> sendDateTime
	{
		get
		{
			return this._sendDateTime;
		}
		set
		{
			if ((this._sendDateTime != value))
			{
				this.OnsendDateTimeChanging(value);
				this.SendPropertyChanging();
				this._sendDateTime = value;
				this.SendPropertyChanged("sendDateTime");
				this.OnsendDateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

public partial class SearchPaidSMsResult
{
	
	private int _ID;
	
	private string _SendFron;
	
	private string _SendTo;
	
	private string _sms;
	
	private string _FlagStatus;
	
	private System.Nullable<System.DateTime> _sendDateTime;
	
	public SearchPaidSMsResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendFron", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
	public string SendFron
	{
		get
		{
			return this._SendFron;
		}
		set
		{
			if ((this._SendFron != value))
			{
				this._SendFron = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendTo", DbType="NVarChar(15)")]
	public string SendTo
	{
		get
		{
			return this._SendTo;
		}
		set
		{
			if ((this._SendTo != value))
			{
				this._SendTo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sms", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string sms
	{
		get
		{
			return this._sms;
		}
		set
		{
			if ((this._sms != value))
			{
				this._sms = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlagStatus", DbType="NVarChar(50)")]
	public string FlagStatus
	{
		get
		{
			return this._FlagStatus;
		}
		set
		{
			if ((this._FlagStatus != value))
			{
				this._FlagStatus = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sendDateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> sendDateTime
	{
		get
		{
			return this._sendDateTime;
		}
		set
		{
			if ((this._sendDateTime != value))
			{
				this._sendDateTime = value;
			}
		}
	}
}
#pragma warning restore 1591
